### PR TITLE
[Issue 382] Fix copy field duplication - merge conflicts resolved

### LINKED ISSUE #382: Prevent duplicate copy fields from being created
Duplicate copy fields are being created even when field creation fails as duplicate.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java [hunk 1]
```diff
@@ -69,17 +69,17 @@ public void init() {
...
-                        SchemaRequest.AddCopyField addCopyFieldRequest = new SchemaRequest.AddCopyField(name, Arrays.asList(fieldType.copyTo()));
-                        addCopyFieldRequest.process(solrClient, collectionName);
-                    } catch (Exception e) {
-                        logger.debug("Failed to add copy field", e);
+                    if (fieldType.copyTo().length > 0) {
+                        try {
+                            SchemaRequest.AddCopyField addCopyFieldRequest = new SchemaRequest.AddCopyField(name, Arrays.asList(fieldType.copyTo()));
+                            addCopyFieldRequest.process(solrClient, collectionName);
+                        } catch (Exception e) {
+                            logger.error("Failed to add copy field", e);
```
Comment (kaladay) [inline src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java:78]: This behavior will succeed to create the field if the only failure is a copy field failure.

Should we fail the entire field if the copy field fails?
This really comes down to the design strategy when handling failures.
I am fine either way.

File: src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java [hunk 2]
```diff
@@ -69,17 +69,17 @@ public void init() {
...
+                        }
                     }
+                } catch (Exception e) {
+                    logger.debug("Failed to add field", e);
```
Comment (kaladay) [inline src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java:82]: If the copy field is `logger.error` should not this be `logger.error` rather than `logger.debug`?

File: src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java (hunk 1 above)
Comment (ghost) [reply src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java:78]: No. We will reserve this for configurability of rolling back the creation of a field. Which is out of scope of the issue.

File: src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java (hunk 2 above)
Comment (ghost) [reply src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java:82]: Not if schematization is unintentionally left on in the configuration. Currently Solr responses are not considered and only if it was successful or not. On restart a bunch of these logs on each instance would not be desired.

Comment (ghost) [reply src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java:82]: Since debugging can be turned on, I prefer this to be a debug log as we have shown deterministic behavior of the indexing process.

**Review by kaladay — APPROVED** [review]
