### PR TITLE
[Issue 347] Add configuration to disable individual document create on batch fail

### LINKED ISSUE #347: Add index configuration to disable try individual on batch fail
Add a property to the index config model to disable iterating over failed batch.

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

File: src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java [hunk 1]
```diff
@@ -119,4 +127,4 @@ private String name() {
         return type.getSimpleName();
     }
 
-}
+}
```
Comment (kaladay) [inline src/main/java/edu/tamu/scholars/middleware/discovery/component/solr/SolrIndexer.java]:
```suggestion

}
```
Add missing trailing new line.
It seems weird to add it here using the code suggest.
I hope it works correctly if used.

**Review by kaladay — CHANGES_REQUESTED** [review]

**Review by kaladay — APPROVED** [review]
